wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  use_address: $ip_address
  fast_connect: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password
