esphome:
  name: ir-blaster-3

esp8266:
  board: esp8285

substitutions:
  ip_address: !secret ir_blaster_3_ip
  command_repeats: "1"

<<: !include base-esphome-configuration.yaml

# remote_receiver:
#   pin:
#     number: GPIO14
#     inverted: true
#   dump: all

remote_transmitter:
  pin:
    number: GPIO4
  carrier_duty_percent: 50%

button:
  - platform: template
    name: "Stars Power"
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBA45
        command_repeats: $command_repeats

  - platform: template
    name: "Stars Toggle Aurora"
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB946
        command_repeats: $command_repeats

  - platform: template
    name: "Stars Toggle Laser"
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB847
        command_repeats: $command_repeats

  - platform: template
    name: "Stars Red"
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBB44
        command_repeats: $command_repeats

  - platform: template
    name: "Stars Blue"
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE916
        command_repeats: $command_repeats

  - platform: template
    name: "Stars Green"
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBC43
        command_repeats: $command_repeats

  - platform: template
    name: "Stars White"
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF20D
        command_repeats: $command_repeats