esphome:
  name: ir-blaster-2

esp8266:
  board: esp8285

substitutions:
  ip_address: !secret ir_blaster_2_ip
  command_repeats: "3"

<<: !include base-esphome-configuration.yaml

# remote_receiver:
#   pin:
#     number: GPIO14
#     inverted: true
#   dump: all

remote_transmitter:
  pin:
    number: GPIO4
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: "Projector Power"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x6B86
        command: 0xF50A
        command_repeats: $command_repeats
  - platform: template
    name: "Projector Mute"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x6B86
        command: 0xB54A
        command_repeats: $command_repeats