esphome:
  name: ir-blaster

esp8266:
  board: esp8285

substitutions:
  ip_address: !secret ir_blaster_ip

<<: !include base-esphome-configuration.yaml

remote_receiver:
  pin:
    number: GPIO14
    inverted: true
  dump: all

remote_transmitter:
  pin:
    number: GPIO4
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: "HDMI Switch In1 Out1"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF50A