esphome:
  name: ir-blaster-2

esp8266:
  board: esp8285

substitutions:
  ip_address: !secret ir_blaster_2_ip
  command_repeats: "2"

<<: !include base-esphome-configuration.yaml

remote_receiver:
  pin:
    number: GPIO14
    inverted: true
  dump: all

