substitutions:
  ip_address: !secret led_dimmer_node_1

esphome:
  name: led-dimmer-node-1
  platform: ESP8266
  board: d1_mini
  on_boot:
    - priority: 600
      then:
        - light.control:
            id: kitchen_light
            brightness: 70%

<<: !include base-esphome-configuration.yaml

output:
  - platform: esp8266_pwm
    pin: D8
    frequency: 5000 Hz
    id: pwm_output

# Example usage in a light
light:
  - platform: monochromatic
    id: kitchen_light
    output: pwm_output
    name: "Kitchen Light"
    default_transition_length: 1.5s

sensor:
  - platform: rotary_encoder
    name: "Kitchen Light Manual Dimmer"
    pin_a: D1
    pin_b: D2
    on_clockwise:
      - light.dim_relative:
          id: kitchen_light
          relative_brightness: 5%
    on_anticlockwise:
      - light.dim_relative:
          id: kitchen_light
          relative_brightness: -5%

binary_sensor:    
  - platform: gpio
    pin: D5
    name: "Kitchen Light Motion Sensor"
    id: led_motion_sensor
    filters:
      - settle: !lambda |-
            if (id(kitchen_light).current_values.is_on()) {
              return 3000;
            } else {
              return 2000;
            }
      - delayed_on_off:
          time_on: !lambda |-
            if (id(kitchen_light).current_values.is_on()) {
              return 0;
            } else {
              return 5000;
            }
          time_off: !lambda |-
            if (id(kitchen_light).current_values.is_on()) {
              return 60000;
            } else {
              return 0;
            }

  - platform: gpio
    pin:
      number: D3
      inverted: true
    name: "Kitchen Light Manual Push Button"
    id: toggle_led
    on_press:
      then:
        light.toggle: kitchen_light
